#!/bin/bash
#
# This script can only be run from the computer on which it was
# originally downloaded.
#
# This auto-generated script was downloaded from http://iotta.snia.org.
# It will download the 56 subtraces of Systor '17 Traces
#
echo "Downloading the 56 subtraces of Systor '17 Traces" 1>&2
cookies=$(mktemp)
cat >> $cookies << 'EOF'
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by iotta.snia.org! Edit at your own risk.

.iotta.snia.org	TRUE	/	FALSE	0	infodigest	1be17021d643167953a68a72a7b2282d8e11b4a5
.iotta.snia.org	TRUE	/	FALSE	0	legal	true
.iotta.snia.org	TRUE	/	FALSE	0	id	628742
EOF

if which wget >/dev/null 2>&1; then
  useWGET=true
elif which curl >/dev/null 2>&1; then
  useCURL=true
else
  echo "Couldn't find either wget or curl. Please install one of them" 1>&2
  exit 1
fi

checkForError() {
  delete=false
  if $useWGET && (( $1 == 2 || $1 == 3 || $1 == 5 || $1 == 7 || $1 == 8 ))
  then
    delete=true
  elif $useWGET && [ ! -s "$2" ]
  then
    delete=true
  elif $useCURL && (( $1 == 22 || $1 == 36 ))
  then
    delete=true
  fi
}

downloadFile() {
  file=$1
  id=$2
  url="http://server2.iotta.snia.org/traces/$id/download?type=file&sType="
  if $useWGET; then
    wget -q --load-cookies=$cookies -O "$file" -c "$url""wget"
  elif $useCURL; then
    curl -s -f -b $cookies -o "$file" -C - -L "$url""curl"
  fi

  if [ $? -eq 0 ]; then
    echo "Finished Downloading $file"
  else 
    checkForError $? "$file"
    if $delete; then
      echo "There was an error downloading the file ($file)"
      rm -f "$file"
    else
      echo "$file was partially downloaded"
    fi
    echo "Stopping..."
    exit 1
  fi
}

downloadFile "systor17-additional-01.tar" 4934
downloadFile "systor17-additional-02.tar" 4937
downloadFile "systor17-additional-03.tar" 4940
downloadFile "systor17-additional-04.tar" 4943
downloadFile "systor17-additional-05.tar" 4946
downloadFile "systor17-additional-06.tar" 4949
downloadFile "systor17-additional-07.tar" 4952
downloadFile "systor17-additional-08.tar" 4955
downloadFile "systor17-additional-09.tar" 4958
downloadFile "systor17-additional-10.tar" 4961
downloadFile "systor17-additional-omitted.tar" 5099
downloadFile "systor17-01.tar" 4967
downloadFile "systor17-02.tar" 4970
downloadFile "systor17-03.tar" 4973
downloadFile "systor17-04.tar" 4976
downloadFile "systor17-05.tar" 4979
downloadFile "systor17-06.tar" 4982
downloadFile "systor17-07.tar" 4985
downloadFile "systor17-08.tar" 4988
downloadFile "systor17-09.tar" 4991
downloadFile "systor17-10.tar" 4994
downloadFile "systor17-11.tar" 4997
downloadFile "systor17-12.tar" 5000
downloadFile "systor17-13.tar" 5003
downloadFile "systor17-14.tar" 5006
downloadFile "systor17-15.tar" 5009
downloadFile "systor17-16.tar" 5012
downloadFile "systor17-17.tar" 5015
downloadFile "systor17-18.tar" 5018
downloadFile "systor17-19.tar" 5021
downloadFile "systor17-20.tar" 5024
downloadFile "systor17-21.tar" 5027
downloadFile "systor17-22.tar" 5030
downloadFile "systor17-23.tar" 5033
downloadFile "systor17-24.tar" 5036
downloadFile "systor17-25.tar" 5039
downloadFile "systor17-26.tar" 5042
downloadFile "systor17-27.tar" 5045
downloadFile "systor17-28.tar" 5048
downloadFile "systor17-29.tar" 5051
downloadFile "systor17-30.tar" 5054
downloadFile "systor17-31.tar" 5057
downloadFile "systor17-32.tar" 5060
downloadFile "systor17-33.tar" 5063
downloadFile "systor17-34.tar" 5066
downloadFile "systor17-35.tar" 5069
downloadFile "systor17-36.tar" 5072
downloadFile "systor17-37.tar" 5075
downloadFile "systor17-38.tar" 5078
downloadFile "systor17-39.tar" 5081
downloadFile "systor17-40.tar" 5084
downloadFile "systor17-41.tar" 5087
downloadFile "systor17-42.tar" 5090
downloadFile "systor17-43.tar" 5093
downloadFile "systor17-44.tar" 5096
downloadFile "systor17-omitted.tar" 5102

echo "Finished All Downloads"
rm -f $cookies
