#!/bin/bash
#
# This script can only be run from the computer on which it was
# originally downloaded.
#
# This auto-generated script was downloaded from http://iotta.snia.org.
# It will download the 2 subtraces of MSR Cambridge Traces
#
echo "Downloading the 2 subtraces of MSR Cambridge Traces" 1>&2
cookies=$(mktemp)
cat >> $cookies << 'EOF'
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by iotta.snia.org! Edit at your own risk.

.iotta.snia.org	TRUE	/	FALSE	0	infodigest	1be17021d643167953a68a72a7b2282d8e11b4a5
.iotta.snia.org	TRUE	/	FALSE	0	legal	true
.iotta.snia.org	TRUE	/	FALSE	0	id	628743
EOF

if which wget >/dev/null 2>&1; then
  useWGET=true
elif which curl >/dev/null 2>&1; then
  useCURL=true
else
  echo "Couldn't find either wget or curl. Please install one of them" 1>&2
  exit 1
fi

checkForError() {
  delete=false
  if $useWGET && (( $1 == 2 || $1 == 3 || $1 == 5 || $1 == 7 || $1 == 8 ))
  then
    delete=true
  elif $useWGET && [ ! -s "$2" ]
  then
    delete=true
  elif $useCURL && (( $1 == 22 || $1 == 36 ))
  then
    delete=true
  fi
}

downloadFile() {
  file=$1
  id=$2
  url="http://server3.iotta.snia.org/traces/$id/download?type=file&sType="
  if $useWGET; then
    wget -q --load-cookies=$cookies -O "$file" -c "$url""wget"
  elif $useCURL; then
    curl -s -f -b $cookies -o "$file" -C - -L "$url""curl"
  fi

  if [ $? -eq 0 ]; then
    echo "Finished Downloading $file"
  else 
    checkForError $? "$file"
    if $delete; then
      echo "There was an error downloading the file ($file)"
      rm -f "$file"
    else
      echo "$file was partially downloaded"
    fi
    echo "Stopping..."
    exit 1
  fi
}

downloadFile "msr-cambridge1.tar" 386
downloadFile "msr-cambridge2.tar" 387

echo "Finished All Downloads"
rm -f $cookies
